### ISSUE TITLE
BWK

### ISSUE THREAD

**Issue by Ev3li3n** [Informatievlaanderen/werkgroep-authentieke-gegevensbronnen#20]
opmerking DIedrik Gaus: BWK (staat deze bron nog steeds op de lijst?): Dienst milieu: Wij hebben net de opdracht gegund aan het INBO (de bronbeheerder van de BWK op Vlaams Niveau) om voor Gent de  meer gedetailleerde BWK verder te verfijnen en actualiseren.
INBO zal dit doen, ook methodiek is afgesproken en komt overeen in beide kaarten. Ik verwacht dan ook dat INBO deze data zal overnemen in hun kaart die dan authentieke bron kan worden, we moeten dan afspraken maken om nadien de actualisaties goed door te laten stromen vanuit Gent => INBO

**Comment by VeerleBeyaert** [comment]
Carine Wils, GIS-coördinator voor Instituut voor Natuur- en Bosonderzoek (INBO): 
 deze actualisatie zal geïntegreerd worden in de bestaande databank en bij de eerstvolgende publicatie mee verwerkt en gepubliceerd worden.
